name = "mtg"
version = "0.1.0"
defaultTargets = ["Mtg.Engine", "mtg-demo"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "Mtg.Engine"

[[lean_lib]]
name = "MtgDemo"
roots = ["Mtg.Demo.WelcomeDecks"]
globs = ["Mtg.Demo.WelcomeDecks"]

[[lean_exe]]
name = "mtg-demo"
root = "Mtg.Demo"
